name: Check Nix Flake

run-name: "Check Nix Flake"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: native

    steps:
      - name: Checkout
        run: |
          git clone --depth=1 --branch "${{ forgejo.head_ref || forgejo.ref_name }}" \
            "https://x-access-token:${{ secrets.FORGEJO_TOKEN }}@$FORGEJO_DOMAIN/${{ forgejo.repository }}" .
      - name: Check formatting
        run: nix fmt -- --ci
      - name: Run nix flake check
        run: nix flake check --impure
