name: Update Nix Flake

run-name: "Update Nix Flake"

on:
  workflow_dispatch:
  schedule:
    # run every thursday
    - cron: '0 0 * * 4'

jobs:
  update:
    runs-on: native

    steps:
      - name: Checkout
        run: |
          git clone --depth=1 --branch "${{ forgejo.ref_name }}" \
            "https://x-access-token:${{ secrets.FORGEJO_TOKEN }}@$FORGEJO_DOMAIN/${{ forgejo.repository }}" .
      - name: Run nix flake update
        run: nix flake update
      - name: Run nix flake check
        run: nix flake check --impure
      - uses: https://github.com/stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: nix flake update"
          commit_user_name: "Forgejo Actions"
          commit_user_email: "noreply@r6b.dev"
