{
 "title": "ZFS Pool Metrics",
 "description": "Dashboard of metrics generated by Richard Elling's cool \"zpool_influxdb\" utility (now included in OpenZFS). ",
 "time": { "from": "2021-12-07T14:29:31.414Z", "to": "2021-12-07T14:41:57.221Z" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "show tag values from \"zpool_stats\" with key = \"host\""
   },
   {
    "name": "poolname",
    "query": "show tag values from \"zpool_stats\" with key = \"name\"  where \"host\" =~ /^$hostname/"
   }
  ]
 },
 "panels": [
  {
   "title": "Pool Activity ($poolname)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zpool_stats",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Write Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Read Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "write_ops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Write Ops" ], "type": "alias" }
      ],
      [
       { "params": [ "read_ops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Read Ops" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "$poolname Pool Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "zpool_stats",
     "select": [
      [
       { "params": [ "size" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "vdev I/O Active Queues ($poolname)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zpool_vdev_stats",
     "select": [
      [
       { "params": [ "sync_w_active_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Sync Write" ], "type": "alias" }
      ],
      [
       { "params": [ "sync_r_active_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Sync Read" ], "type": "alias" }
      ],
      [
       { "params": [ "async_scrub_active_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Async Scrub" ], "type": "alias" }
      ],
      [
       { "params": [ "async_w_active_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Async Write" ], "type": "alias" }
      ],
      [
       { "params": [ "async_r_active_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Async Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_stats",
     "select": [
      [
       { "params": [ "read_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Read Errors" ], "type": "alias" }
      ],
      [
       { "params": [ "write_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Write Errors" ], "type": "alias" }
      ],
      [
       { "params": [ "fragmentation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Fragmentation" ], "type": "alias" }
      ],
      [
       { "params": [ "checksum_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Checksum Errors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
      { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_stats",
     "select": [
      [
       { "params": [ "alloc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Alloc" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
      { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
     ]
    }
   ]
  },
  {
   "title": "vdev I/O Pending Queues ($poolname)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zpool_vdev_stats",
     "select": [
      [
       { "params": [ "sync_w_pend_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Sync Write" ], "type": "alias" }
      ],
      [
       { "params": [ "sync_r_pend_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Sync Read" ], "type": "alias" }
      ],
      [
       { "params": [ "async_scrub_pend_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Async Scrub" ], "type": "alias" }
      ],
      [
       { "params": [ "async_w_pend_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Async Write" ], "type": "alias" }
      ],
      [
       { "params": [ "async_r_pend_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Async Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Usage ($poolname)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zpool_stats",
     "select": [
      [
       { "params": [ "alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Allocated" ], "type": "alias" }
      ],
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Size" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "fragmentation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Fragmentation" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
      { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
     ]
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Reads",
   "type": "heatmap",
   "description": "Latency histogram for the total reads of a ZFS pool",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "$tag_le",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "le" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_latency",
     "select": [
      [
       { "params": [ "total_read" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
      { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
     ]
    }
   ]
  },
  {
   "title": "Total Writes",
   "type": "heatmap",
   "description": "Latency histogram for the total writes of a ZFS pool",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 15 },
   "targets": [
    {
     "alias": "$tag_le",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "le" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_latency",
     "select": [
      [
       { "params": [ "total_write" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
      { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
     ]
    }
   ]
  },
  {
   "title": "Sync Read Queue",
   "type": "heatmap",
   "description": "Latency histogram for the synchronous reads of a ZFS pool",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 23 },
   "targets": [
    {
     "alias": "$tag_le",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "le" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_latency",
     "select": [
      [
       { "params": [ "sync_read" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "Async Read Queue",
   "type": "heatmap",
   "description": "Latency histogram for the asynchronous reads of a ZFS pool",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 23 },
   "targets": [
    {
     "alias": "$tag_le",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "le" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_latency",
     "select": [
      [
       { "params": [ "async_read" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "Scrub/Scan Read Queue",
   "type": "heatmap",
   "description": "Latency histogram for the scrub or scan reads of a ZFS pool",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 23 },
   "targets": [
    {
     "alias": "$tag_le",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "le" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_latency",
     "select": [
      [
       { "params": [ "scrub" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Read Queue",
   "type": "heatmap",
   "description": "Latency histogram for the actual disk reads of a ZFS pool",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 23 },
   "targets": [
    {
     "alias": "$tag_le",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "le" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_latency",
     "select": [
      [
       { "params": [ "disk_read" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "Sync Write Queue",
   "type": "heatmap",
   "description": "Latency histogram for the synchronous writes of a ZFS pool",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 31 },
   "targets": [
    {
     "alias": "$tag_le",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "le" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_latency",
     "select": [
      [
       { "params": [ "sync_write" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "Async Write Queue",
   "type": "heatmap",
   "description": "Latency histogram for the asynchronous writes of a ZFS pool",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 31 },
   "targets": [
    {
     "alias": "$tag_le",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "le" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_latency",
     "select": [
      [
       { "params": [ "async_write" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "Trim Write Queue",
   "type": "heatmap",
   "description": "Latency histogram for the trim or unmap operations of a ZFS pool",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 31 },
   "targets": [
    {
     "alias": "$tag_le",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "le" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_latency",
     "select": [
      [
       { "params": [ "trim" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Write Queue",
   "type": "heatmap",
   "description": "Latency histogram for the disk write operations of a ZFS pool",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 31 },
   "targets": [
    {
     "alias": "$tag_le",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "le" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_latency",
     "select": [
      [
       { "params": [ "disk_write" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "Logical (Individual) I/O Sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logical Async Reads",
     "type": "heatmap",
     "description": "Latency histogram for the total writes of a ZFS pool",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
     "targets": [
      {
       "alias": "$tag_le",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "le" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zpool_io_size",
       "select": [
        [
         { "params": [ "async_read_ind" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
        { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
       ]
      }
     ]
    },
    {
     "title": "Logical Sync Reads",
     "type": "heatmap",
     "description": "Latency histogram for the total writes of a ZFS pool",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
     "targets": [
      {
       "alias": "$tag_le",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "le" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zpool_io_size",
       "select": [
        [
         { "params": [ "sync_read_ind" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
        { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
       ]
      }
     ]
    },
    {
     "title": "Logical Scrub Reads",
     "type": "heatmap",
     "description": "Latency histogram for the total writes of a ZFS pool",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
     "targets": [
      {
       "alias": "$tag_le",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "le" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zpool_io_size",
       "select": [
        [
         { "params": [ "scrub_read_ind" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
        { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
       ]
      }
     ]
    },
    {
     "title": "Logical Async Writes",
     "type": "heatmap",
     "description": "Latency histogram for the total writes of a ZFS pool",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "targets": [
      {
       "alias": "$tag_le",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "le" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zpool_io_size",
       "select": [
        [
         { "params": [ "async_write_ind" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
        { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
       ]
      }
     ]
    },
    {
     "title": "Logical Sync Writes",
     "type": "heatmap",
     "description": "Latency histogram for the total writes of a ZFS pool",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
     "targets": [
      {
       "alias": "$tag_le",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "le" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zpool_io_size",
       "select": [
        [
         { "params": [ "sync_write_ind" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
        { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
       ]
      }
     ]
    },
    {
     "title": "Logical Trim Writes",
     "type": "heatmap",
     "description": "Latency histogram for the total writes of a ZFS pool",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
     "targets": [
      {
       "alias": "$tag_le",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "le" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zpool_io_size",
       "select": [
        [
         { "params": [ "trim_write_ind" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
        { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Physical (Aggregated) I/O Sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Physical Async Reads",
     "type": "heatmap",
     "description": "Latency histogram for the total writes of a ZFS pool",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "targets": [
      {
       "alias": "$tag_le",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "le" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zpool_io_size",
       "select": [
        [
         { "params": [ "async_read_agg" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
        { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
       ]
      }
     ]
    },
    {
     "title": "Physical Sync Reads",
     "type": "heatmap",
     "description": "Latency histogram for the total writes of a ZFS pool",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "targets": [
      {
       "alias": "$tag_le",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "le" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zpool_io_size",
       "select": [
        [
         { "params": [ "sync_read_agg" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
        { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
       ]
      }
     ]
    },
    {
     "title": "Physical Scrub Reads",
     "type": "heatmap",
     "description": "Latency histogram for the total writes of a ZFS pool",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "targets": [
      {
       "alias": "$tag_le",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "le" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zpool_io_size",
       "select": [
        [
         { "params": [ "scrub_read_agg" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
        { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
       ]
      }
     ]
    },
    {
     "title": "Physical Async Writes",
     "type": "heatmap",
     "description": "Latency histogram for the total writes of a ZFS pool",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
     "targets": [
      {
       "alias": "$tag_le",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "le" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zpool_io_size",
       "select": [
        [
         { "params": [ "async_write_agg" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
        { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
       ]
      }
     ]
    },
    {
     "title": "Physical Sync Writes",
     "type": "heatmap",
     "description": "Latency histogram for the total writes of a ZFS pool",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
     "targets": [
      {
       "alias": "$tag_le",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "le" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zpool_io_size",
       "select": [
        [
         { "params": [ "sync_write_agg" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
        { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
       ]
      }
     ]
    },
    {
     "title": "Physical Trim Writes",
     "type": "heatmap",
     "description": "Latency histogram for the total writes of a ZFS pool",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
     "targets": [
      {
       "alias": "$tag_le",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "le" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zpool_io_size",
       "select": [
        [
         { "params": [ "trim_write_agg" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
        { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
       ]
      }
     ]
    }
   ]
  }
 ]
}