
name: update-flakes
on:
  workflow_dispatch:
  schedule:
    - cron: "40 4 * * 0,2,4,6"

jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@v3
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true

      - uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update flake.lock
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          nix flake update --commit-lock-file

      - name: Set default git branch (to reduce log spam)
        run: git config --global init.defaultBranch master

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: flake-updates
          delete-branch: true
          title: "Update flake.lock"
          body: |
            ## Run report
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"